{% set name = "libassuan" %}
{% set version = "3.0.0" %}
{% set sha256 = "0b160cbb898b852c6c04314b9a63e90ca87501305ad72a58a010f808665bbaf6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libassuan', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make       # [unix]
    - libtool    # [unix]
    - automake   # [unix]
    - gnuconfig  # [unix]
  host:
    - libgpg-error

test:
  commands:

about:
  home: https://www.gnupg.org/software/libassuan/index.html
  summary: Libassuan is a small library implementing the so-called Assuan protocol.
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  description: |
    Libassuan is a small library implementing the so-called Assuan protocol.
    This protocol is used for IPC between most newer GnuPG components.

extra:
  recipe-maintainers:
    - mariusvniekerk
